[WIP]ユーザープロフィール編集ページ
THitokuse/mercari pull request #16
Opened 2019-02-16 12:27 UTC by nezuu

# what
ユーザープロフィール編集ページ

# why
ユーザーがプロフィール情報を変更できるようにするため

[![Screenshot from Gyazo](https://gyazo.com/b9ed18fbeed29dcc5ad2df6474ddd815/raw)](https://gyazo.com/b9ed18fbeed29dcc5ad2df6474ddd815)

2019-02-16 12:30 UTC, yuki-uchida requested changes

2019-02-16 12:30 UTC, yuki-uchida commented on app/assets/stylesheets/mypage/profile.scss
> +.setting-profile-content {
BEMというクラス命名記法に乗っ取ってクラスの名前づけを行いましょう。
それに伴って、アンバサンドで省略形でCSSを記述しましょう
https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-16 12:47 UTC, nezuu commented on app/assets/stylesheets/mypage/profile.scss
> +.setting-profile-content {
二箇所、BEMに乗っ取ったクラス名に修正しました！

ネストしている子要素のcssは、もともとあるcssに追加しているのですが、クラス名を２つつけてあげたほうがよろしいのでしょうか？

2019-02-16 12:53 UTC, yuki-uchida commented on app/assets/stylesheets/mypage/profile.scss
> +.setting-profile-content {
>ネストしている子要素のcssは、もともとあるcssに追加しているのですが、クラス名を２つつけてあげたほうがよろしいのでしょうか？

こちら、子要素の名前を変更した場合には、CSSもそれに伴って変更する必要があります。
もともとあるCSSとはどういう意味でしょうか？基本的にはBEMの記法では、
親の親--親__子といった名前になり、cssでは
親の親{
  親{
     子{
      }
  }
}

といった書き方になります。

2019-02-16 12:55 UTC, yuki-uchida requested changes

2019-02-16 12:55 UTC, yuki-uchida commented on app/assets/stylesheets/mypage/profile.scss
> +  .textarea-default {
こちらであれば、setting-profile__content_textareaのような名前にし、CSSはネストする形で書くことによって、親の名前を継承し、&__textareaといった省略形で記述することができます

2019-02-16 12:55 UTC, yuki-uchida commented on app/assets/stylesheets/mypage/profile.scss
> +  .btn-red {
こちらも、親の名前をきちんと使ったクラス名にしましょう

2019-02-17 02:27 UTC, nezuu commented on app/assets/stylesheets/mypage/profile.scss
> +.setting-profile-content {
大変ご丁寧なご教授ありがとうございます！
こちらの大きな勘違いでした！
BEMに乗っ取り修正しました。

2019-02-17 02:34 UTC, nezuu commented on app/assets/stylesheets/mypage/profile.scss
> +  .btn-red {
修正しました！

2019-02-17 02:34 UTC, nezuu commented on app/assets/stylesheets/mypage/profile.scss
> +  .textarea-default {
修正しました！

2019-02-17 02:36 UTC, nezuu commented
## 変更点 
・BEMに乗っ取りクラス名を変更しました
・それに伴い、cssを当て直しました。

2019-02-17 02:38 UTC, yuki-uchida approved these changes
よくかけてると思います！！！LGTMですお疲れ様でした

2019-02-17 02:39 UTC, merged