[WIP]商品出品画面のMVCの設定
THitokuse/mercari pull request #8
Opened 2019-02-05 21:42 UTC by Yuri-Kosaki

WHAT: 商品出品画面を表示させるためのMVCを実装した
WHY: 本番のメルカリにあったため。

2019-02-06 02:04 UTC, miyagit reviewed
コメントしました。

2019-02-06 02:04 UTC, miyagit commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
itemimagesという命名が変な気がしますね。

2019-02-06 02:04 UTC, miyagit commented on app/views/items/new.html.haml
> +                        %option{value: "1"} レディース
ymlなどにまとめて出すようにしましょう。

2019-02-06 02:04 UTC, miyagit commented on app/views/items/new.html.haml
> +                        %option{value: ""} ---
こちらも同じです。

2019-02-07 12:41 UTC, Yuri-Kosaki commented on app/views/items/new.html.haml
> +                        %option{value: "1"} レディース
修正しました。

2019-02-07 12:41 UTC, Yuri-Kosaki commented on app/views/items/new.html.haml
> +                        %option{value: ""} ---
修正しました。

2019-02-07 12:42 UTC, Yuri-Kosaki commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
そもそものモデル名をitemimagesにしているので、変更は難しいです。

2019-02-07 12:43 UTC, Yuri-Kosaki commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
違うモデル名に変えたほうがいいですか？

2019-02-07 12:43 UTC, Yuri-Kosaki commented
コメントしました。

2019-02-07 12:49 UTC, yuki-uchida requested changes

2019-02-07 12:49 UTC, yuki-uchida commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
そうですね、モデル名として、スニークケースかキャメルケースがいいのか調べましょう。
名前としてitemimagesはどちらでも無いので、良くないです

2019-02-07 12:49 UTC, yuki-uchida commented on app/views/items/new.html.haml
> +              %a.btn-default.btn-gray もどる
link_to使いましょう

2019-02-07 13:46 UTC, Yuri-Kosaki commented on app/views/items/new.html.haml
> +              %a.btn-default.btn-gray もどる
修正しました。

2019-02-07 13:46 UTC, Yuri-Kosaki commented
コメントしました。

2019-02-07 15:55 UTC, THitokuse commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
@Yuri-Kosaki 
モデル名をスネークケースにしましょう！もしかしたら自分がモデル作ったとき、そのままにしてたのかもしれないです。申し訳ない。
モデルのクラス名をItemImageにしてこっちを呼び出して行きましょう。

もしかしたらコンフリクトが起こるかもしれなので、git diffで確認していきます。
面倒ですが、これでいきましょう！

2019-02-07 16:03 UTC, Yuri-Kosaki commented on app/controllers/items_controller.rb
> +    @item.itemimages.build
@THitokuse 
モデル名をスネークケースに変更したので、大丈夫です。
LGTMいただいたら、masterにマージするので、プルして頂ければコンフリクトも大丈夫だと思います。

2019-02-08 02:02 UTC, TOMARUMARU approved these changes
LGTM

2019-02-08 03:42 UTC, Yuri-Kosaki commented
WHAT: 商品出品画面のSCSSを記述した。 
WHY:  ユーザーに出品の操作をやりやすくするため。

2019-02-08 03:46 UTC, Yuri-Kosaki commented
![localhost_3000_items_new](https://user-images.githubusercontent.com/24793349/52457905-8dc80080-2b9f-11e9-965e-ac03d3d993ce.png)

2019-02-08 03:50 UTC, miyagit commented on app/assets/stylesheets/sell/sell_header.scss
> +
改行削除しましょう。

2019-02-08 03:50 UTC, miyagit commented on config/locales/ja.yml
> +    category:
モデルごとにjaファイル作った方が良いですね。

2019-02-08 09:10 UTC, Yuri-Kosaki commented on app/assets/stylesheets/sell/sell_header.scss
> +
修正しました。

2019-02-08 09:10 UTC, Yuri-Kosaki commented on config/locales/ja.yml
> +    category:
修正しました。

2019-02-08 09:25 UTC, kuroko918 commented
このプルリクなのですが、WHAT/WHYが二ヶ所あり、機能的に２つ実装しているかと思うのですが...今回はしょうがないので、このまま進めていきましょう。

一度、conflictを解消してください！

2019-02-08 10:24 UTC, merged